#!/usr/bin/env python3
"""Format CodeGiraffe review results as a PR comment.

Usage:
    python format-pr-comment.py review-results.json
    python format-pr-comment.py  # reads review-results.json by default
"""

import json
import sys


def format_comment(results: dict) -> str:
    """Format review results as a markdown PR comment.

    Parameters
    ----------
    results:
        Dictionary with keys:
        - changed_files: list of file path strings
        - blast_radius: list of {"file": str, "downstream_count": int}
        - test_suggestions: list of test file path strings

    Returns
    -------
    str
        Markdown-formatted comment body.
    """
    lines = ["## CodeGiraffe Architectural Review\n"]

    # Changed files summary
    changed = results.get("changed_files", [])
    lines.append(f"**Changed files:** {len(changed)}\n")

    # Blast radius impact table
    blast = results.get("blast_radius", [])
    if blast:
        lines.append("### Impact Analysis\n")
        lines.append("| File | Downstream Nodes |")
        lines.append("|------|-----------------|")
        for item in blast:
            lines.append(f"| `{item['file']}` | {item['downstream_count']} nodes |")
        lines.append("")

    # Test suggestions
    tests = results.get("test_suggestions", [])
    if tests:
        lines.append("### Suggested Tests\n")
        for t in tests:
            lines.append(f"- {t}")
        lines.append("")

    lines.append("---")
    lines.append(
        "*Generated by [CodeGiraffe](https://github.com/jthom233/CodeGiraffe)*"
    )

    return "\n".join(lines)


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "review-results.json"
    with open(path) as f:
        results = json.load(f)
    print(format_comment(results))
